using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Line_98.Components
{
    internal class BadWordFilter
    {
        private HashSet<string> _badWords;

        /// <summary>
        /// Khởi tạo danh sách các từ thô tục trong tiếng Anh và tiếng Việt
        /// </summary>
        public BadWordFilter()
        {
            
            _badWords = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                // Danh sách các từ thô tục (tiếng Anh)
                "abbo", "abo", "abortion", "abuse", "addict", "addicts", "adult", "africa", "african", "alla", "allah", "alligatorbait", "amateur", "american", "anal", "analannie", "analsex", "angie", "angry", "anus", "arab", "arabs", "areola", "argie", "aroused", "arse", "arsehole", "asian", "ass", "assassin", "assassinate", "assassination", "assault", "assbagger", "assblaster", "assclown", "asscowboy", "asses", "assfuck", "assfucker", "asshat", "asshole", "assholes", "asshore", "assjockey", "asskiss", "asskisser", "assklown", "asslick", "asslicker", "asslover", "assman", "assmonkey", "assmunch", "assmuncher", "asspacker", "asspirate", "asspuppies", "assranger", "asswhore", "asswipe", "athletesfoot", "attack", "australian",
                "babe", "babies", "backdoor", "backdoorman", "backseat", "badfuck", "balllicker", "balls", "ballsack", "banging", "baptist", "barelylegal", "barf", "barface", "barfface", "bast", "bastard ", "bazongas", "bazooms", "beaner", "beast", "beastality", "beastial", "beastiality", "beatoff", "beat-off", "beatyourmeat", "beaver", "bestial", "bestiality", "bi", "biatch", "bible", "bicurious", "bigass", "bigbastard", "bigbutt", "bigger", "bisexual", "bi-sexual", "bitch", "bitcher", "bitches", "bitchez", "bitchin", "bitching", "bitchslap", "bitchy", "biteme", "black", "blackman", "blackout", "blacks", "blind", "blow", "blowjob", "boang", "bogan", "bohunk", "bollick", "bollock", "bomb", "bombers", "bombing", "bombs", "bomd", "bondage", "boner", "bong", "boob", "boobies", "boobs", "booby", "boody", "boom", "boong", "boonga", "boonie", "booty", "bootycall", "bountybar", "bra", "brea5t", "breast", "breastjob", "breastlover", "breastman", "brothel", "bugger", "buggered", "buggery", "bullcrap", "bulldike", "bulldyke", "bullshit", "bumblefuck", "bumfuck", "bunga", "bunghole", "buried", "burn", "butchbabes", "butchdike", "butchdyke", "butt", "buttbang", "butt-bang", "buttface", "buttfuck", "butt-fuck", "buttfucker", "butt-fucker", "buttfuckers", "butt-fuckers", "butthead", "buttman", "buttmunch", "buttmuncher", "buttpirate", "buttplug", "buttstain", "byatch",
                "cacker", "cameljockey", "cameltoe", "canadian", "cancer", "carpetmuncher", "carruth", "catholic", "catholics", "cemetery", "chav", "cherrypopper", "chickslick", "children's", "chin", "chinaman", "chinamen", "chinese", "chink", "chinky", "choad", "chode", "christ", "christian", "church", "cigarette", "cigs", "clamdigger", "clamdiver", "clit", "clitoris", "clogwog", "cocaine", "cock", "cockblock", "cockblocker", "cockcowboy", "cockfight", "cockhead", "cockknob", "cocklicker", "cocklover", "cocknob", "cockqueen", "cockrider", "cocksman", "cocksmith", "cocksmoker", "cocksucer", "cocksuck ", "cocksucked ", "cocksucker", "cocksucking", "cocktail", "cocktease", "cocky", "cohee", "coitus", "color", "colored", "coloured", "commie", "communist", "condom", "conservative", "conspiracy", "coolie", "cooly", "coon", "coondog", "copulate", "cornhole", "corruption", "cra5h", "crabs", "crack", "crackpipe", "crackwhore", "crack-whore", "crap", "crapola", "crapper", "crappy", "crash", "creamy", "crime", "crimes", "criminal", "criminals", "crotch", "crotchjockey", "crotchmonkey", "crotchrot", "cum", "cumbubble", "cumfest", "cumjockey", "cumm", "cummer", "cumming", "cumquat", "cumqueen", "cumshot", "cunilingus", "cunillingus", "cunn", "cunnilingus", "cunntt", "cunt", "cunteyed", "cuntfuck", "cuntfucker", "cuntlick ", "cuntlicker ", "cuntlicking ", "cuntsucker", "cybersex", "cyberslimer", 
                "dago", "dahmer", "dammit", "damn", "damnation", "damnit", "darkie", "darky", "datnigga", "dead", "deapthroat", "death", "deepthroat", "defecate", "dego", "demon", "deposit", "desire", "destroy", "deth", "devil", "devilworshipper", "dick", "dickbrain", "dickforbrains", "dickhead", "dickless", "dicklick", "dicklicker", "dickman", "dickwad", "dickweed", "diddle", "die", "died", "dies", "dike", "dildo", "dingleberry", "dink", "dipshit", "dipstick", "dirty", "disease", "diseases", "disturbed", "dive", "dix", "dixiedike", "dixiedyke", "doggiestyle", "doggystyle", "dong", "doodoo", "doo-doo", "doom", "dope", "dragqueen", "dragqween", "dripdick", "drug", "drunk", "drunken", "dumb", "dumbass", "dumbbitch", "dumbfuck", "dyefly", "dyke", 
                "easyslut", "eatballs", "eatme", "eatpussy", "ecstacy", "ejaculate", "ejaculated", "ejaculating ", "ejaculation", "enema", "enemy", "erect", "erection", "ero", "escort", "ethiopian", "ethnic", "european", "evl", "excrement", "execute", "executed", "execution", "executioner", "explosion", 
                "facefucker", "faeces", "fag", "fagging", "faggot", "fagot", "failed", "failure", "fairies", "fairy", "faith", "fannyfucker", "fart", "farted ", "farting ", "farty ", "fastfuck", "fat", "fatah", "fatass", "fatfuck", "fatfucker", "fatso", "fckcum", "fear", "feces", "felatio ", "felch", "felcher", "felching", "fellatio", "feltch", "feltcher", "feltching", "fetish", "fight", "filipina", "filipino", "fingerfood", "fingerfuck ", "fingerfucked ", "fingerfucker ", "fingerfuckers", "fingerfucking ", "fire", "firing", "fister", "fistfuck", "fistfucked ", "fistfucker ", "fistfucking ", "fisting", "flange", "flasher", "flatulence", "floo", "flydie", "flydye", "fok", "fondle", "footaction", "footfuck", "footfucker", "footlicker", "footstar", "fore", "foreskin", "forni", "fornicate", "foursome", "fourtwenty", "fraud", "freakfuck", "freakyfucker", "freefuck", "fu", "fubar", "fuc", "fucck", "fuck", "fucka", "fuckable", "fuckbag", "fuckbuddy", "fucked", "fuckedup", "fucker", "fuckers", "fuckface", "fuckfest", "fuckfreak", "fuckfriend", "fuckhead", "fuckher", "fuckin", "fuckina", "fucking", "fuckingbitch", "fuckinnuts", "fuckinright", "fuckit", "fuckknob", "fuckme ", "fuckmehard", "fuckmonkey", "fuckoff", "fuckpig", "fucks", "fucktard", "fuckwhore", "fuckyou", "fudgepacker", "fugly", "fuk", "fuks", "funeral", "funfuck", "fungus", "fuuck",
                "gangbang", "gangbanged ", "gangbanger", "gangsta", "gatorbait", "gay", "gaymuthafuckinwhore", "gaysex ", "geez", "geezer", "geni", "genital", "german", "getiton", "gin", "ginzo", "gipp", "girls", "givehead", "glazeddonut", "gob", "god", "godammit", "goddamit", "goddammit", "goddamn", "goddamned", "goddamnes", "goddamnit", "goddamnmuthafucker", "goldenshower", "gonorrehea", "gonzagas", "gook", "gotohell", "goy", "goyim", "greaseball", "gringo", "groe", "gross", "grostulation", "gubba", "gummer", "gun", "gyp", "gypo", "gypp", "gyppie", "gyppo", "gyppy", 
                "hamas", "handjob", "hapa", "harder", "hardon", "harem", "headfuck", "headlights", "hebe", "heeb", "hell", "henhouse", "heroin", "herpes", "heterosexual", "hijack", "hijacker", "hijacking", "hillbillies", "hindoo", "hiscock", "hitler", "hitlerism", "hitlerist", "hiv", "ho", "hobo", "hodgie", "hoes", "hole", "holestuffer", "homicide", "homo", "homobangers", "homosexual", "honger", "honk", "honkers", "honkey", "honky", "hook", "hooker", "hookers", "hooters", "hore", "hork", "horn", "horney", "horniest", "horny", "horseshit", "hosejob", "hoser", "hostage", "hotdamn", "hotpussy", "hottotrot", "hummer", "husky", "hussy", "hustler", "hymen", "hymie", 
                "iblowu", "idiot", "ikey", "illegal", "incest", "insest", "intercourse", "interracial", "intheass", "inthebuff", "israel", "israeli", "israel's", "italiano", "itch", 
                "jackass", "jackoff", "jackshit", "jacktheripper", "jade", "jap", "japanese", "japcrap", "jebus", "jeez", "jerkoff", "jesus", "jesuschrist", "jew", "jewish", "jiga", "jigaboo", "jigg", "jigga", "jiggabo", "jigger ", "jiggy", "jihad", "jijjiboo", "jimfish", "jism", "jiz ", "jizim", "jizjuice", "jizm ", "jizz", "jizzim", "jizzum", "joint", "juggalo", "jugs", "junglebunny", 
                "kaffer", "kaffir", "kaffre", "kafir", "kanake", "kid", "kigger", "kike", "kill", "killed", "killer", "killing", "kills", "kink", "kinky", "kissass", "kkk", "knife", "knockers", "kock", "kondum", "koon", "kotex", "krap", "krappy", "kraut", "kum", "kumbubble", "kumbullbe", "kummer", "kumming", "kumquat", "kums", "kunilingus", "kunnilingus", "kunt", "ky", "kyke", 
                "lactate", "laid", "lapdance", "latin", "lesbain", "lesbayn", "lesbian", "lesbin", "lesbo", "lez", "lezbe", "lezbefriends", "lezbo", "lezz", "lezzo", "liberal", "libido", "licker", "lickme", "lies", "limey", "limpdick", "limy", "lingerie", "liquor", "livesex", "loadedgun", "lolita", "looser", "loser", "lotion", "lovebone", "lovegoo", "lovegun", "lovejuice", "lovemuscle", "lovepistol", "loverocket", "lowlife", "lsd", "lubejob", "lucifer", "luckycammeltoe", "lugan", "lynch", 
                "macaca", "mad", "mafia", "magicwand", "mams", "manhater", "manpaste", "marijuana", "mastabate", "mastabater", "masterbate", "masterblaster", "mastrabator", "masturbate", "masturbating", "mattressprincess", "meatbeatter", "meatrack", "meth", "mexican", "mgger", "mggor", "mickeyfinn", "mideast", "milf", "minority", "mockey", "mockie", "mocky", "mofo", "moky", "moles", "molest", "molestation", "molester", "molestor", "moneyshot", "mooncricket", "mormon", "moron", "moslem", "mosshead", "mothafuck", "mothafucka", "mothafuckaz", "mothafucked ", "mothafucker", "mothafuckin", "mothafucking ", "mothafuckings", "motherfuck", "motherfucked", "motherfucker", "motherfuckin", "motherfucking", "motherfuckings", "motherlovebone", "muff", "muffdive", "muffdiver", "muffindiver", "mufflikcer", "mulatto", "muncher", "munt", "murder", "murderer", "muslim", 
                "naked", "narcotic", "nasty", "nastybitch", "nastyho", "nastyslut", "nastywhore", "nazi", "necro", "negro", "negroes", "negroid", "negro's", "nig", "niger", "nigerian", "nigerians", "nigg", "nigga", "niggah", "niggaracci", "niggard", "niggarded", "niggarding", "niggardliness", "niggardliness's", "niggardly", "niggards", "niggard's", "niggaz", "nigger", "niggerhead", "niggerhole", "niggers", "nigger's", "niggle", "niggled", "niggles", "niggling", "nigglings", "niggor", "niggur", "niglet", "nignog", "nigr", "nigra", "nigre", "nip", "nipple", "nipplering", "nittit", "nlgger", "nlggor", "nofuckingway", "nook", "nookey", "nookie", "noonan", "nooner", "nude", "nudger", "nuke", "nutfucker", "nymph", 
                "ontherag", "oral", "orga", "orgasim ", "orgasm", "orgies", "orgy", "osama", 
                "paki", "palesimian", "palestinian", "pansies", "pansy", "panti", "panties", "payo", "pearlnecklace", "peck", "pecker", "peckerwood", "pee", "peehole", "pee-pee", "peepshow", "peepshpw", "pendy", "penetration", "peni5", "penile", "penis", "penises", "penthouse", "period", "perv", "phonesex", "phuk", "phuked", "phuking", "phukked", "phukking", "phungky", "phuq", "pi55", "picaninny", "piccaninny", "pickaninny", "piker", "pikey", "piky", "pimp", "pimped", "pimper", "pimpjuic", "pimpjuice", "pimpsimp", "pindick", "piss", "pissed", "pisser", "pisses ", "pisshead", "pissin ", "pissing", "pissoff ", "pistol", "pixie", "pixy", "playboy", "playgirl", "pocha", "pocho", "pocketpool", "pohm", "polack", "pom", "pommie", "pommy", "poo", "poon", "poontang", "poop", "pooper", "pooperscooper", "pooping", "poorwhitetrash", "popimp", "porchmonkey", "porn", "pornflick", "pornking", "porno", "pornography", "pornprincess", "pot", "poverty", "premature", "pric", "prick", "prickhead", "primetime", "propaganda", "pros", "prostitute", "protestant", "pu55i", "pu55y", "pube", "pubic", "pubiclice", "pud", "pudboy", "pudd", "puddboy", "puke", "puntang", "purinapricness", "puss", "pussie", "pussies", "pussy", "pussycat", "pussyeater", "pussyfucker", "pussylicker", "pussylips", "pussylover", "pussypounder", "pusy", 
                "quashie", "queef", "queer", "quickie", "quim", 
                "ra8s", "rabbi", "racial", "racist", "radical", "radicals", "raghead", "randy", "rape", "raped", "raper", "rapist", "rearend", "rearentry", "rectum", "redlight", "redneck", "reefer", "reestie", "refugee", "reject", "remains", "rentafuck", "republican", "rere", "retard", "retarded", "ribbed", "rigger", "rimjob", "rimming", "roach", "robber", "roundeye", "rump", "russki", "russkie", 
                "sadis", "sadom", "samckdaddy", "sandm", "sandnigger", "satan", "scag", "scallywag", "scat", "schlong", "screw", "screwyou", "scrotum", "scum", "semen", "seppo", "servant", "sex", "sexed", "sexfarm", "sexhound", "sexhouse", "sexing", "sexkitten", "sexpot", "sexslave", "sextogo", "sextoy", "sextoys", "sexual", "sexually", "sexwhore", "sexy", "sexymoma", "sexy-slim", "shag", "shaggin", "shagging", "shat", "shav", "shawtypimp", "sheeney", "shhit", "shinola", "shit", "shitcan", "shitdick", "shite", "shiteater", "shited", "shitface", "shitfaced", "shitfit", "shitforbrains", "shitfuck", "shitfucker", "shitfull", "shithapens", "shithappens", "shithead", "shithouse", "shiting", "shitlist", "shitola", "shitoutofluck", "shits", "shitstain", "shitted", "shitter", "shitting", "shitty ", "shoot", "shooting", "shortfuck", "showtime", "sick", "sissy", "sixsixsix", "sixtynine", "sixtyniner", "skank", "skankbitch", "skankfuck", "skankwhore", "skanky", "skankybitch", "skankywhore", "skinflute", "skum", "skumbag", "slant", "slanteye", "slapper", "slaughter", "slav", "slave", "slavedriver", "sleezebag", "sleezeball", "slideitin", "slime", "slimeball", "slimebucket", "slopehead", "slopey", "slopy", "slut", "sluts", "slutt", "slutting", "slutty", "slutwear", "slutwhore", "smack", "smackthemonkey", "smut", "snatch", "snatchpatch", "snigger", "sniggered", "sniggering", "sniggers", "snigger's", "sniper", "snot", "snowback", "snownigger", "sob", "sodom", "sodomise", "sodomite", "sodomize", "sodomy", "sonofabitch", "sonofbitch", "sooty", "sos", "soviet", "spaghettibender", "spaghettinigger", "spank", "spankthemonkey", "sperm", "spermacide", "spermbag", "spermhearder", "spermherder", "spic", "spick", "spig", "spigotty", "spik", "spit", "spitter", "splittail", "spooge", "spreadeagle", "spunk", "spunky", "squaw", "stagg", "stiffy", "strapon", "stringer", "stripclub", "stroke", "stroking", "stupid", "stupidfuck", "stupidfucker", "suck", "suckdick", "sucker", "suckme", "suckmyass", "suckmydick", "suckmytit", "suckoff", "suicide", "swallow", "swallower", "swalow", "swastika", "sweetness", "syphilis", 
                "taboo", "taff", "tampon", "tang", "tantra", "tarbaby", "tard", "teat", "terror", "terrorist", "teste", "testicle", "testicles", "thicklips", "thirdeye", "thirdleg", "threesome", "threeway", "timbernigger", "tinkle", "tit", "titbitnipply", "titfuck", "titfucker", "titfuckin", "titjob", "titlicker", "titlover", "tits", "tittie", "titties", "titty", "tnt", "toilet", "tongethruster", "tongue", "tonguethrust", "tonguetramp", "tortur", "torture", "tosser", "towelhead", "trailertrash", "tramp", "trannie", "tranny", "transexual", "transsexual", "transvestite", "triplex", "trisexual", "trojan", "trots", "tuckahoe", "tunneloflove", "turd", "turnon", "twat", "twink", "twinkie", "twobitwhore", 
                "uck", "uk", "unfuckable", "upskirt", "uptheass", "upthebutt", "urinary", "urinate", "urine", "usama", "uterus",
                "vagina", "vaginal", "vatican", "vibr", "vibrater", "vibrator", "vietcong", "violence", "virgin", "virginbreaker", "vomit", "vulva", 
                "wab", "wank", "wanker", "wanking", "waysted", "weapon", "weenie", "weewee", "welcher", "welfare", "wetb", "wetback", "wetspot", "whacker", "whash", "whigger", "whiskey", "whiskeydick", "whiskydick", "whit", "whitenigger", "whites", "whitetrash", "whitey", "whiz", "whop", "whore", "whorefucker", "whorehouse", "wigger", "willie", "williewanker", "willy", "wn", "wog", "women's", "wop", "wtf", "wuss", "wuzzie", 
                "xtc", "xxx", 
                "yankee", "yellowman", 
                "zigabo", "zipperhead",
                // Danh sách các từ thô tục (Tiếng Việt)
                "4`",
                "an lol", "an lon",
                "b`", "banh háng", "banh lol", "banh lon", "bitch", "biz", "bo me", "bo mia", "bo mie", "bo mja", "bo mje", "bucak", "buoi", "buscu", "buồi", "bà cha mày", "bít chi", "bòi", "bỏ bú", "bỏ mja", "bỏ mje", "bỏ mẹ", "bỏ mịa", "bỏ mịe", "bố láo",
                "cac", "cai lol", "cai lon", "caiconcac", "caiconcak", "caidauboi", "caidauboy", "caidaubuoi", "cailon", "cak", "cak", "cao lol", "cao lon", "cdi~", "chet me", "chet mia", "chet mie", "chet mja", "chet mje", "chetme", "chich", "chich choac", "chó má", "chó điên", "chết mie", "chết mja", "chết mẹ", "chết mịa", "chết mịe", "chịch", "chổng mông", "cl", "clgt", "cmn", "cmnl", "con bic", "con bíc", "con bích", "con bít", "con di cho", "con di cho'", "con lol", "con lon", "concak", "condi", "condicho", "condimay", "condime", "condimemay", "condi~", "cu", "cu lol", "cu lon", "cuccut", "cuk", "cutcut", "cào lol", "cào lon", "cái lol", "cái lon", "cái lề gì thốn", "cái lờ", "cđĩ", "cười ẻ", "cười ỉa", "cặc", "cặk", "cờ hó", "cờ lờ gờ tờ", "củ lol", "củ lon", "cứk", "cứt", 
                "d'", "dach lol", "dach lon", "dau boi", "dau boy", "dau buoi", "dauboi", "dauboy", "daubuoi", "dcm", "dcmm", "dcmmm", "dcmmmm", "dech", "dek", "del", "dell an", "dell biet", "dell biết", "dell chay", "dell chiu", "dell chạy", "dell chịu", "dell di", "dell duoc", "dell hieu", "dell hiểu", "dell lam", "dell làm", "dell nghe", "dell ngui", "dell ngửi", "dell noi", "dell nói", "dell ăn", "dell đi", "dell được", "dellhieukieugi", "dellnoinhieu", "deo", "deohieukieugi", "di me", "dilol", "dilon", "diloz", "dime", "dimemay", "diml", "dis", "dis me", "dis mia", "dis mie", "disme", "dismia", "dismje", "dit", "ditmeconcho", "ditmecondi", "ditmecondicho", "ditmemay", "ditmemayconcho", "ditmethangoccho", "diz", "di~", "djt", "dm", "dmconcho", "dmcs", "dml", "dmm", "dmmm", "dmmmm", "dmmmmm", "doma", "dou", "dou ma", "dou má", "duo má", "duoma", "dái",
                "fck", "fuck",
                "giái",
                "ham lol", "ham lon", "hãm", "húp sò", "kac", "kak", "ke me", "ke mia", "ke mie", "ke mja", "ke mje", "kiu", "kệ mja", "kệ mje", "kệ mẹ", "kệ mịa", "kệ mịe",
                "l`", "la liếm", "lao cho", "loi lol", "loi lon", "loz", "láo chó", "lìn", "lòi lol", "lòi lon", "lồn",
                "ma cha may", "ma cha nha may", "mat lol", "mat lol", "mat lon", "mat lon", "matlol", "matlon", "matloz", "me cha may", "me cha nha may", "ml", "mom lol", "mom lon", "mu lol", "mu lon", "mát lol", "mát lol", "mát lon", "mát lon", "mõm lol", "mõm lon", "mả cha", "mả cha mày", "mả cha nhà mày", "mả mẹ", "mặt lol", "mặt lon", "mẹ bà", "mẹ cha anh", "mẹ cha mày", "mẹ cha nhà anh", "mẹ cha nhà mày", "mồm lol", "mồm lon",
                "ngu", "ngu lol", "ngu lon", "nhu lol", "nhu lon", "nhucaidaubuoi", "như lol", "như lon", "nug", "nug lol", "nug lon", "nuglol", "nuglon", "nulo", "nung lol", "nung lon", "nungcak", "nốn lừng", "nứng", "nứng lol", "nứng lon", 
                "occho",
                "phò", 
                "ranh lol", "ranh lon", "rảnh lol", "rảnh lon", 
                "sap mat", "sapmatlol", "sapmatlon", "sapmatloz", "sml", "sảng", "sấp mặt", "sủa bậy", "sủa càn", "sủa tiếp", "sủa đi", 
                "tet lol", "tet lon", "thang cho", "thang cho'", "thang dien", "thangmatlon", "thangml", "thay me", "thay mia", "thay mie", "thml", "thml", "thấy mẹ", "thấy mịa", "thấy mịe", "thằng chó", "thằng điên", "tiên sư bố", "tiên sư nhà mày", "tml", "tung lol", "tung lon", "tuoi lol", "tuoi lon", "tuổi lol", "tuổi lon", "tét lol", "tét lon", "tổ cha", "tổ sư", 
                "vach lol", "vach lon", "vai lol", "vai lon", "vailol", "vailon", "vcl", "vl", "vleu", "vlol", "vlon", "vloz", "v~", "vãi", "vạch lol", "vạch lon", "xam lol", "xam lon", "xao lol", "xao lon", "xephinh", "xhct", "xoac", "xoạc", "xàm lol", "xàm lon", "xéo háng", "xạo lol", "xạo lon", "zái", 
                "á đìu", "á đù", "óc chó", "ăn lol", "ăn lon", 
                "đ'", "đcm", "đcmm", "đcmmm", "đcmmmm", "đel", "đilol", "đilon", "điloz", "đis mịa", "đis mịe", "điếm", "đjt", "đm", "đmm", "đmmm", "đmmmm", "đmmmmm", "đou má", "đuỹ", "đách", "đách lol", "đách lon", "đél", "đéo", "đê ma ma", "đê mama", "đê mờ", "đìu", "đìu má", "đù cha", "đù má", "đù mẹ", "đù mịa", "đù mịe", "đú cha", "đú con mẹ", "đú má", "đú mẹ", "đút đít", "đĩ", "đầu bòy", "đầu bùi", "đậu má", "đậu mẹ", "đếch", "đếk", "đết", "đề ma ma", "đề mama", "đệch", "đệt", "đệt", "địt", "địt ba", "địt bà", "địt bố", "địt cha", "địt con", "địt cụ", "địt má", "địt mía", "địt mẹ", "địt mịe", "đốn cửa lòng", "đồ điên", "đổ vỏ", "đỗn lì", "đờ ma ma", "đờ mama", "đờ mờ", "đụ", "đụ", "đụ", "đụ bà", "đụ cha", "đụ má", "đụ mẹ", "đụ mịa", "đụ mịe", "đủ cha", "đủ mia", "đủ mie", "đủ má", "đủ mé", "đủ mía", "đủ mẹ", "đủ mịa", "đủ mịe",
                // Danh sách các từ thô tục (Tiếng Việt, bỏ dấu cách)
                "4`",
                "anlol","anlon",
                "b`","banhháng","banhlol","banhlon","bitch","biz","bome","bomia","bomie","bomja","bomje","bucak","buoi","buscu","buồi","bàchamày","bítchi","bòi","bỏbú","bỏmja","bỏmje","bỏmẹ","bỏmịa","bỏmịe","bốláo",
                "cac","cailol","cailon","caiconcac","caiconcak","caidauboi","caidauboy","caidaubuoi","cailon","cak","cak","caolol","caolon","cdi~","chetme","chetmia","chetmie","chetmja","chetmje","chetme","chich","chichchoac","chómá","chóđiên","chếtmie","chếtmja","chếtmẹ","chếtmịa","chếtmịe","chịch","chổngmông","cl","clgt","cmn","cmnl","conbic","conbíc","conbích","conbít","condicho","condicho'","conlol","conlon","concak","condi","condicho","condimay","condime","condimemay","condi~","cu","culol","culon","cuccut","cuk","cutcut","càolol","càolon","cáilol","cáilon","cáilềgìthốn","cáilờ","cđĩ","cườiẻ","cườiỉa","cặc","cặk","cờhó","cờlờgờtờ","củlol","củlon","cứk","cứt",
                "d'","dachlol","dachlon","dauboi","dauboy","daubuoi","dauboi","dauboy","daubuoi","dcm","dcmm","dcmmm","dcmmmm","dech","dek","del","dellan","dellbiet","dellbiết","dellchay","dellchiu","dellchạy","dellchịu","delldi","dellduoc","dellhieu","dellhiểu","delllam","delllàm","dellnghe","dellngui","dellngửi","dellnoi","dellnói","dellăn","dellđi","dellđược","dellhieukieugi","dellnoinhieu","deo","deohieukieugi","dime","dilol","dilon","diloz","dime","dimemay","diml","dis","disme","dismia","dismie","disme","dismia","dismje","dit","ditmeconcho","ditmecondi","ditmecondicho","ditmemay","ditmemayconcho","ditmethangoccho","diz","di~","djt","dm","dmconcho","dmcs","dml","dmm","dmmm","dmmmm","dmmmmm","doma","dou","douma","doumá","duomá","duoma","dái",
                "fck","fuck",
                "giái",
                "hamlol","hamlon","hãm","húpsò","kac","kak","keme","kemia","kemie","kemja","kemje","kiu","kệmja","kệmje","kệmẹ","kệmịa","kệmịe",
                "l`","laliếm","laocho","loilol","loilon","loz","láochó","lìn","lòilol","lòilon","lồn",
                "machamay","machanhamay","matlol","matlol","matlon","matlon","matlol","matlon","matloz","mechamay","mechanhamay","ml","momlol","momlon","mulol","mulon","mátlol","mátlol","mátlon","mátlon","mõmlol","mõmlon","mảcha","mảchamày","mảchanhàmày","mảmẹ","mặtlol","mặtlon","mẹbà","mẹchaanh","mẹchamày","mẹchanhàanh","mẹchanhàmày","mồmlol","mồmlon",
                "ngu","ngulol","ngulon","nhulol","nhulon","nhucaidaubuoi","nhưlol","nhưlon","nug","nuglol","nuglon","nuglol","nuglon","nulo","nunglol","nunglon","nungcak","nốnlừng","nứng","nứnglol","nứnglon",
                "occho",
                "phò",
                "ranhlol","ranhlon","rảnhlol","rảnhlon",
                "sapmat","sapmatlol","sapmatlon","sapmatloz","sml","sảng","sấpmặt","sủabậy","sủacàn","sủatiếp","sủađi",
                "tetlol","tetlon","thangcho","thangcho'","thangdien","thangmatlon","thangml","thayme","thaymia","thaymie","thml","thml","thấymẹ","thấymịa","thấymịe","thằngchó","thằngđiên","tiênsưbố","tiênsưnhàmày","tml","tunglol","tunglon","tuoilol","tuoilon","tuổilol","tuổilon","tétlol","tétlon","tổcha","tổsư",
                "vachlol","vachlon","vailol","vailon","vailol","vailon","vcl","vl","vleu","vlol","vlon","vloz","v~","vãi","vạchlol","vạchlon","xamlol","xamlon","xaolol","xaolon","xephinh","xhct","xoac","xoạc","xàmlol","xàmlon","xéoháng","xạolol","xạolon","zái",
                "áđìu","áđù","ócchó","ănlol","ănlon",
                "đ'","đcm","đcmm","đcmmm","đcmmmm","đel","đilol","đilon","điloz","đismịa","đismịe","điếm","đjt","đm","đmm","đmmm","đmmmm","đmmmmm","đoumá","đuỹ","đách","đáchlol","đáchlon","đél","đéo","đêmama","đêmama","đêmờ","đìu","đìumá","đùcha","đùmá","đùmẹ","đùmịa","đùmịe","đúcha","đúconmẹ","đúmá","đúmẹ","đútđít","đĩ","đầubòy","đầubùi","đậumá","đậumẹ","đếch","đếk","đết","đềmama","đềmama","đệch","đệt","đệt","địt","địtba","địtbà","địtbố","địtcha","địtcon","địtcụ","địtmá","địtmía","địtmẹ","địtmịe","đốncửalòng","đồđiên","đổvỏ","đỗnlì","đờmama","đờmama","đờmờ","đụ","đụ","đụ","đụbà","đụcha","đụmá","đụmẹ","đụmịa","đụmịe","đủcha","đủmia","đủmie","đủmá","đủmé","đủmía","đủmẹ","đủmịa","đủmịe",
            };
        }

        /// <summary>
        /// Kiểm tra có xuất hiện từ thô tục trong xâu không
        /// </summary>
        /// <returns>True/False</returns>
        public bool ContainsBadWord(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return false;

            string lowerText = text.ToLower();

            foreach (string badWord in _badWords)
            {
                // Pattern: badWord có thể đứng một mình hoặc có ký tự không phải chữ số/chữ cái ở 2 đầu
                string pattern = $@"\b{Regex.Escape(badWord)}\b";

                if (Regex.IsMatch(lowerText, pattern, RegexOptions.IgnoreCase))
                    return true;

                // Hoặc kiểm tra cả trường hợp không có boundary
                if (lowerText.Contains(badWord))
                    return true;
            }

            return false;
        }
        /// <summary>
        /// Kiểm tra xâu có phải là một từ thô tục không
        /// </summary>
        /// <returns>True/False</returns>
        public bool IsBadWord(string word)
        {
            return _badWords.Contains(word?.ToLower() ?? "");
        }
    }
}
